# Nombre del servidor 
servidor.nombre=\SQLEXPRESS
# Usuario para la conexi\uFFFDn
servidor.usuario =sa
# Password para la conexi\uFFFDn
servidor.password=admin123
# Puerto de Conexi\uFFFDn
servidor.port=1433
# Nombre Base datos
bd.name=TaqueriaBD2
# Controlador de SqlServer
servidor.control=jdbc:sqlserver
# Ip Servidor
ip=localhost